### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by calebd**

### CODE REVIEW

**Comment by calebd** [comment]
Ready for you to review @cocoahero!

**Comment by calebd** [comment]
I'm ready to go on this with the exception of the comment I left in 23b444f.

**Comment by cocoahero** [comment]
I like it.

Things I would like to see added at some point:
- Examples of `EncoderType` in README.
- Test cases for `EncoderType`.
- Headerdoc across the board, especially the framework provided `DecoderType`'s.

In terms of an extension directly on `SequenceType`, my only apprehension is what to call the function.

**Comment by calebd** [comment]
Something like this:

``` swift
extension SequenceType {
    func encode<T: EncoderType where T.Value == Generator.Element>(encoder: T.Type) -> JSON {
        // Encode
    }
}
```

That would only extend `SequenceType` where its value type is the same as the provided `DecoderType`.

I like this a little better because you can chain the operations more cleanly. `value.paragraphs.encode(ParagraphEncoder)` vs `ParagraphEncoder.encode(value.paragraphs)`. It also feels more natural next to the rest of our API.

**Comment by cocoahero** [comment]
Sounds good to me. Do you want to have both and just have one delegate to the other?

**Pull request merged**
